name = "bitrot-pours"
main = "index.ts"
compatibility_date = "2026-04-12"

routes = [
  { pattern = "api.bitrot.timothybrits.co.za", custom_domain = true }
]

[placement]
mode = "smart"

[observability]
enabled = true

[observability.logs]
enabled = true

[observability.traces]
enabled = true

[[kv_namespaces]]
binding = "POURS"
id = "f37c7fead51c46d59b48ac5bb6e600e3"
preview_id = "f37c7fead51c46d59b48ac5bb6e600e3"

[vars]
ALLOWED_ORIGIN = "https://bitrot.timothybrits.co.za"
